# Generated by Django 5.2 on 2025-04-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
